### ISSUE TITLE
Heroku crashes on 2.0.0-p247

### ISSUE THREAD

**Issue by borisd** [heroku/legacy-cli#1038]
heroku                                                                                                                            [ruby-2.0.0-p247]  18:02
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb:67: [BUG] Segmentation fault
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin10.8.0]

-- Control frame information -----------------------------------------------
c:0023 p:---- s:0072 b:0072 l:000071 d:000071 CFUNC  :initialize
c:0022 p:---- s:0070 b:0070 l:000069 d:000069 CFUNC  :new
c:0021 p:0099 s:0067 b:0065 l:000064 d:000064 METHOD /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb:67
c:0020 p:0090 s:0056 b:0055 l:000054 d:000054 CLASS  /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:17
c:0019 p:0011 s:0053 b:0053 l:000052 d:000052 CLASS  /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:12
c:0018 p:0074 s:0051 b:0051 l:000050 d:000050 TOP    /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:9
c:0017 p:---- s:0049 b:0049 l:000048 d:000048 FINISH
c:0016 p:---- s:0047 b:0047 l:000046 d:000046 CFUNC  :require
c:0015 p:0027 s:0043 b:0043 l:000042 d:000042 CLASS  /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json.rb:58
c:0014 p:0021 s:0041 b:0041 l:000040 d:000040 TOP    /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json.rb:54
c:0013 p:---- s:0039 b:0039 l:000038 d:000038 FINISH
c:0012 p:---- s:0037 b:0037 l:000036 d:000036 CFUNC  :require
c:0011 p:0023 s:0033 b:0033 l:000032 d:000032 TOP    /Users/boris/.heroku/client/lib/heroku/command/ps.rb:2
c:0010 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0009 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :require
c:0008 p:0012 s:0025 b:0025 l:000016 d:000024 BLOCK  /Users/boris/.heroku/client/lib/heroku/command.rb:14
c:0007 p:---- s:0022 b:0022 l:000021 d:000021 FINISH
c:0006 p:---- s:0020 b:0020 l:000019 d:000019 CFUNC  :each
c:0005 p:0051 s:0017 b:0017 l:000016 d:000016 METHOD /Users/boris/.heroku/client/lib/heroku/command.rb:13
c:0004 p:0090 s:0014 b:0014 l:000013 d:000013 METHOD /Users/boris/.heroku/client/lib/heroku/cli.rb:27
c:0003 p:0232 s:0008 b:0008 l:0002d8 d:0013b8 EVAL   /usr/local/heroku/bin/heroku:24
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0002d8 d:0002d8 TOP   

-- Ruby level backtrace information ----------------------------------------
/usr/local/heroku/bin/heroku:24:in `<main>'
/Users/boris/.heroku/client/lib/heroku/cli.rb:27:in`start'
/Users/boris/.heroku/client/lib/heroku/command.rb:13:in `load'
/Users/boris/.heroku/client/lib/heroku/command.rb:13:in`each'
/Users/boris/.heroku/client/lib/heroku/command.rb:14:in `block in load'
/Users/boris/.heroku/client/lib/heroku/command.rb:14:in`require'
/Users/boris/.heroku/client/lib/heroku/command/ps.rb:2:in `<top (required)>'
/Users/boris/.heroku/client/lib/heroku/command/ps.rb:2:in`require'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json.rb:54:in `<top (required)>'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json.rb:58:in`module:JSON'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json.rb:58:in `require'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:9:in`<top (required)>'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:12:in `<module:JSON>'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext.rb:17:in`module:Ext'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb:67:in `generator='
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb:67:in`new'
/Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb:67:in `initialize'

-- C level backtrace information -------------------------------------------

   See Crash Report log file under ~/Library/Logs/CrashReporter or
   /Library/Logs/CrashReporter, for the more detail of.

-- Other runtime information -----------------------------------------------
- Loaded script: /usr/local/heroku/bin/heroku
- Loaded features:
  
  0 enumerator.so
  1 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/encdb.bundle
  2 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/trans/transdb.bundle
  3 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/defaults.rb
  4 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/rbconfig.rb
  5 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/deprecate.rb
  6 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/exceptions.rb
  7 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/custom_require.rb
  8 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems.rb
  9 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/pathname.bundle
  10 /usr/local/heroku/ruby/lib/ruby/1.9.1/pathname.rb
  11 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/user_interaction.rb
  12 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/etc.bundle
  13 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/config_file.rb
  14 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/version.rb
  15 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/rubygems_integration.rb
  16 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/requirement.rb
  17 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/dependency.rb
  18 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/shared_helpers.rb
  19 /usr/local/heroku/ruby/lib/ruby/1.9.1/fileutils.rb
  20 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_path_manipulation.rb
  21 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/platform.rb
  22 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/specification.rb
  23 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/gem_helpers.rb
  24 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/match_platform.rb
  25 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/rubygems_ext.rb
  26 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/version.rb
  27 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler.rb
  28 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/settings.rb
  29 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/path_support.rb
  30 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/digest.bundle
  31 /usr/local/heroku/ruby/lib/ruby/1.9.1/digest.rb
  32 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/digest/sha1.bundle
  33 /usr/local/heroku/ruby/lib/ruby/1.9.1/set.rb
  34 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/definition.rb
  35 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/dependency.rb
  36 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/ruby_dsl.rb
  37 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/dsl.rb
  38 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/source.rb
  39 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/common.rb
  40 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/generic.rb
  41 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/ftp.rb
  42 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/http.rb
  43 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/https.rb
  44 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/ldap.rb
  45 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/ldaps.rb
  46 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri/mailto.rb
  47 /usr/local/heroku/ruby/lib/ruby/1.9.1/uri.rb
  48 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/remote_fetcher.rb
  49 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/errors.rb
  50 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/text.rb
  51 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/spec_fetcher.rb
  52 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb
  53 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/source/path.rb
  54 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/source/git.rb
  55 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/strscan.bundle
  56 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/lockfile_parser.rb
  57 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb
  58 /usr/local/heroku/ruby/lib/ruby/1.9.1/tsort.rb
  59 /usr/local/heroku/ruby/lib/ruby/1.9.1/forwardable.rb
  60 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/spec_set.rb
  61 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/environment.rb
  62 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/runtime.rb
  63 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/index.rb
  64 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/remote_specification.rb
  65 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/endpoint_specification.rb
  66 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/source/git/git_proxy.rb
  67 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/dep_proxy.rb
  68 /usr/local/heroku/ruby/lib/ruby/1.9.1/rubygems/source_index.rb
  69 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/bundler-1.3.5/lib/bundler/setup.rb
  70 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/stringio.bundle
  71 /usr/local/heroku/lib/vendor/heroku/okjson.rb
  72 /usr/local/heroku/lib/heroku/helpers.rb
  73 /usr/local/heroku/lib/heroku/updater.rb
  74 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parseexception.rb
  75 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/formatters/default.rb
  76 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/formatters/pretty.rb
  77 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/node.rb
  78 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/child.rb
  79 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parent.rb
  80 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/xmltokens.rb
  81 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/namespace.rb
  82 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/encoding.rb
  83 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/source.rb
  84 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/entity.rb
  85 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/attlistdecl.rb
  86 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/doctype.rb
  87 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/text.rb
  88 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/attribute.rb
  89 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/cdata.rb
  90 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/functions.rb
  91 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/syncenumerator.rb
  92 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parsers/xpathparser.rb
  93 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/xpath_parser.rb
  94 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/xpath.rb
  95 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/element.rb
  96 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/xmldecl.rb
  97 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/comment.rb
  98 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/instruction.rb
  99 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/rexml.rb
  100 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/output.rb
  101 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/undefinednamespaceexception.rb
  102 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parsers/baseparser.rb
  103 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parsers/streamparser.rb
  104 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/validation/validationexception.rb
  105 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/parsers/treeparser.rb
  106 /usr/local/heroku/ruby/lib/ruby/1.9.1/rexml/document.rb
  107 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/date_core.bundle
  108 /usr/local/heroku/ruby/lib/ruby/1.9.1/date/format.rb
  109 /usr/local/heroku/ruby/lib/ruby/1.9.1/date.rb
  110 /usr/local/heroku/ruby/lib/ruby/1.9.1/time.rb
  111 /usr/local/heroku/ruby/lib/ruby/1.9.1/cgi/core.rb
  112 /usr/local/heroku/ruby/lib/ruby/1.9.1/cgi/cookie.rb
  113 /usr/local/heroku/ruby/lib/ruby/1.9.1/cgi/util.rb
  114 /usr/local/heroku/ruby/lib/ruby/1.9.1/cgi.rb
  115 /Users/boris/.heroku/client/vendor/gems/netrc-0.7.7/lib/netrc.rb
  116 /Users/boris/.heroku/client/lib/heroku/auth.rb
  117 /Users/boris/.heroku/client/lib/heroku/plugin.rb
  118 /Users/boris/.heroku/client/lib/heroku/version.rb
  119 /usr/local/heroku/ruby/lib/ruby/1.9.1/optparse.rb
  120 /Users/boris/.heroku/client/lib/heroku/command.rb
  121 /Users/boris/.heroku/client/lib/heroku/client/ssl_endpoint.rb
  122 /Users/boris/.heroku/client/lib/heroku/client.rb
  123 /Users/boris/.heroku/client/lib/heroku.rb
  124 /Users/boris/.heroku/client/lib/heroku/cli.rb
  125 /usr/local/heroku/ruby/lib/ruby/1.9.1/timeout.rb
  126 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/socket.bundle
  127 /usr/local/heroku/ruby/lib/ruby/1.9.1/socket.rb
  128 /Users/boris/.heroku/client/lib/heroku/client/rendezvous.rb
  129 /usr/local/heroku/ruby/lib/ruby/1.9.1/base64.rb
  130 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/openssl.bundle
  131 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/bn.rb
  132 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/cipher.rb
  133 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/config.rb
  134 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/digest.rb
  135 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/buffering.rb
  136 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/fcntl.bundle
  137 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/ssl-internal.rb
  138 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/x509-internal.rb
  139 /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl.rb
  140 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/zlib.bundle
  141 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/utils.rb
  142 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/constants.rb
  143 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/connection.rb
  144 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/errors.rb
  145 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/base.rb
  146 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/decompress.rb
  147 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/expects.rb
  148 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/idempotent.rb
  149 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/instrumentor.rb
  150 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/mock.rb
  151 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/redirect_follower.rb
  152 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/middlewares/response_parser.rb
  153 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/response.rb
  154 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/socket.rb
  155 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/ssl_socket.rb
  156 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/unix_socket.rb
  157 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon/standard_instrumentor.rb
  158 /Users/boris/.heroku/client/vendor/gems/excon-0.31.0/lib/excon.rb
  159 /Users/boris/.heroku/client/vendor/gems/multi_json-1.8.4/lib/multi_json/options.rb
  160 /Users/boris/.heroku/client/vendor/gems/multi_json-1.8.4/lib/multi_json/version.rb
  161 /Users/boris/.heroku/client/vendor/gems/multi_json-1.8.4/lib/multi_json/load_error.rb
  162 /Users/boris/.heroku/client/vendor/gems/multi_json-1.8.4/lib/multi_json.rb
  163 /usr/local/heroku/ruby/lib/ruby/1.9.1/securerandom.rb
  164 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/errors.rb
  165 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/addons.rb
  166 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/apps.rb
  167 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/attachments.rb
  168 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/collaborators.rb
  169 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/config_vars.rb
  170 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/domains.rb
  171 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/features.rb
  172 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/keys.rb
  173 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/login.rb
  174 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/logs.rb
  175 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/processes.rb
  176 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/releases.rb
  177 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/stacks.rb
  178 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock/user.rb
  179 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/mock.rb
  180 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/version.rb
  181 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/addons.rb
  182 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/apps.rb
  183 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/attachments.rb
  184 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/collaborators.rb
  185 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/config_vars.rb
  186 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/domains.rb
  187 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/features.rb
  188 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/keys.rb
  189 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/login.rb
  190 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/logs.rb
  191 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/processes.rb
  192 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/releases.rb
  193 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/ssl_endpoints.rb
  194 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/stacks.rb
  195 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api/user.rb
  196 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku/api.rb
  197 /Users/boris/.heroku/client/vendor/gems/heroku-api-0.3.17/lib/heroku-api.rb
  198 /Users/boris/.heroku/client/lib/heroku/client/organizations.rb
  199 /Users/boris/.heroku/client/lib/heroku/command/base.rb
  200 /Users/boris/.heroku/client/lib/heroku/command/account.rb
  201 /Users/boris/.heroku/client/lib/heroku/command/accounts.rb
  202 /Users/boris/.heroku/client/lib/heroku/helpers/heroku_postgresql.rb
  203 /Users/boris/.heroku/client/lib/heroku/command/addons.rb
  204 /Users/boris/.heroku/client/lib/heroku/command/apps.rb
  205 /Users/boris/.heroku/client/lib/heroku/command/auth.rb
  206 /Users/boris/.heroku/client/lib/heroku/command/certs.rb
  207 /Users/boris/.heroku/client/lib/heroku/command/config.rb
  208 /Users/boris/.heroku/client/lib/heroku/command/domains.rb
  209 /Users/boris/.heroku/client/lib/heroku/command/drains.rb
  210 /Users/boris/.heroku/client/lib/heroku/client/cisaurus.rb
  211 /Users/boris/.heroku/client/lib/heroku/command/fork.rb
  212 /Users/boris/.heroku/client/lib/heroku/command/git.rb
  213 /Users/boris/.heroku/client/lib/heroku/deprecated.rb
  214 /Users/boris/.heroku/client/lib/heroku/deprecated/help.rb
  215 /Users/boris/.heroku/client/lib/heroku/command/help.rb
  216 /Users/boris/.heroku/client/lib/heroku/command/keys.rb
  217 /Users/boris/.heroku/client/lib/heroku/command/labs.rb
  218 /Users/boris/.heroku/client/lib/heroku/helpers/log_displayer.rb
  219 /Users/boris/.heroku/client/lib/heroku/command/logs.rb
  220 /Users/boris/.heroku/client/lib/heroku/command/maintenance.rb
  221 /Users/boris/.heroku/client/lib/heroku/command/members.rb
  222 /Users/boris/.heroku/client/lib/heroku/command/orgs.rb
  223 /Users/boris/.heroku/client/lib/heroku/client/heroku_postgresql.rb
  224 /Users/boris/.heroku/client/lib/heroku/helpers/pg_dump_restore.rb
  225 /Users/boris/.heroku/client/lib/heroku/command/pg.rb
  226 /Users/boris/.heroku/client/lib/heroku/client/pgbackups.rb
  227 /Users/boris/.heroku/client/lib/heroku/command/pgbackups.rb
  228 /Users/boris/.heroku/client/lib/heroku/command/plugins.rb
  229 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/version.rb
  230 /usr/local/heroku/ruby/lib/ruby/1.9.1/ostruct.rb
  231 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/generic_object.rb
  232 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/common.rb
  233 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/utf_16be.bundle
  234 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/utf_16le.bundle
  235 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/utf_32be.bundle
  236 /usr/local/heroku/ruby/lib/ruby/1.9.1/x86_64-darwin10.8.0/enc/utf_32le.bundle
  237 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext/parser.bundle
  238 /Users/boris/.rvm/gems/ruby-2.0.0-p247/gems/json-1.8.1/lib/json/ext/generator.bundle

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Looks like it is trying to use 1.9.1 and 2.0.0 at the same time

**Comment by trimble** [comment]
Looking to clean things up in the archives...this issue seems to have been overcome by time and events. Can we close this one?
