### ISSUE TITLE
"Heroku::Client rendezvous fixup hash" fails when output redirected

### ISSUE THREAD

**Issue by voxik** [heroku/legacy-cli#1119]
This commit https://github.com/heroku/heroku/commit/79c63a76874ae5ed5d3bdaeb8680ba30e7b5835a introduces following test case:

```
it "hash" do
  @rendezvous.send(:fixup, { :x => :y }).should eq({ :x => :y })
end
```

Running the test with output redirection it fails:

```
$ rspec ./spec/heroku/client/rendezvous_spec.rb:20 | cat
Run options: include {:locations=>{"./spec/heroku/client/rendezvous_spec.rb"=>[20]}}
F

Failures:

  1) Heroku::Client rendezvous fixup hash
     Failure/Error: @rendezvous.send(:fixup, { :x => :y }).should eq({ :x => :y })
     NoMethodError:
       undefined method `gsub' for {:x=>:y}:Hash
     # ./lib/heroku/client/rendezvous.rb:109:in `fixup'
     # ./spec/heroku/client/rendezvous_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 0.00059 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/heroku/client/rendezvous_spec.rb:20 # Heroku::Client rendezvous fixup hash

Randomized with seed 60126
```

Either the test or the method should be fixed.

Interestingly, it is passing on travis, where I'd expect output redirected to the file and it seems that older webmock up to 1.10.2 is hiding this error (and probably also other issues), when entire test suite is executed at once.

**Comment by voxik** [comment]
This is still issue for 3.30.3.

**Comment by voxik** [comment]
Still breaks for 3.41.3 :/
