### ISSUE TITLE
heroku fork gives bad URI(is not URI?):  (URI::InvalidURIError)

### ISSUE THREAD

**Issue by taylor** [heroku/legacy-cli#1142]
Transferring database (this can take some time)... Failed to fork app discovery-austin-staging to discovery-austin-staging-127.

....

```
Error:       bad URI(is not URI?):  (URI::InvalidURIError)
Backtrace:   /home/taylor/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:176:in `split'
             /home/taylor/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
             /home/taylor/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
             /home/taylor/.heroku/client/lib/heroku/client/pgbackups.rb:9:in `initialize'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:136:in `new'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:136:in `block in migrate_db'
             /home/taylor/.heroku/client/lib/heroku/helpers.rb:227:in `action'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:130:in `migrate_db'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:76:in `block in index'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:51:in `each'
             /home/taylor/.heroku/client/lib/heroku/command/fork.rb:51:in `index'
             /home/taylor/.heroku/client/lib/heroku/command.rb:218:in `run'
             /home/taylor/.heroku/client/lib/heroku/cli.rb:37:in `start'
             /usr/local/heroku/bin/heroku:24:in `<main>'

Command:     heroku fork -a discovery-austin-staging
Plugins:     heroku-config
Version:     heroku-toolbelt/3.9.1 (x86_64-linux) ruby/2.0.0
```

**Comment by harisiri74** [comment]
I see same problem here..is this resolved ? whats the fix ?
