### ISSUE TITLE
Heroku fails to load on ubuntu 14.04, given this error message

### ISSUE THREAD

**Issue by dtytomi** [heroku/legacy-cli#1198]
```
usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- openssl (LoadError)
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/vendor/gems/excon-0.33.0/lib/excon.rb:6:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/vendor/gems/heroku-api-0.3.18/lib/heroku/api.rb:3:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/vendor/gems/heroku-api-0.3.18/lib/heroku-api.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/lib/heroku/client/organizations.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/lib/heroku/command/base.rb:4:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/lib/heroku/command/releases.rb:1:in `<top (required)>'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/heroku/lib/heroku/command.rb:14:in `block in load'
    from /usr/local/heroku/lib/heroku/command.rb:13:in `each'
    from /usr/local/heroku/lib/heroku/command.rb:13:in `load'
    from /usr/local/heroku/lib/heroku/cli.rb:36:in `start'
    from /usr/bin/heroku:25:in `<main>'
```

**Comment by vishal-patel17** [comment]
how did you resolved it?

**Comment by dtytomi** [comment]
Well, if I may ask do you have ruby installed.
