### ISSUE TITLE
Windows toolbelt + pg:extras fails to run vacuum-stats

### ISSUE THREAD

**Issue by ghidinelli** [heroku/legacy-cli#1222]
Successfully  installed pg:extras and have used all the commands but one:

```
>heroku pg:vacuum_stats DATABASE_URL --app <appname>
psql: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       psql failed. exit status 512, output: "" (RuntimeError)
    Backtrace:   C:/Users/brian/.heroku/client/lib/heroku/command/pg.rb:579:in `exec_sql_on_uri'
                 C:/Users/brian/.heroku/client/lib/heroku/command/pg.rb:569:in `exec_sql'
                 C:/Users/brian/.heroku/plugins/heroku-pg-extras/lib/heroku/command/pg.rb:555:in `vacuum_stats'
                 C:/Users/brian/.heroku/client/lib/heroku/command.rb:217:in `run'
                 C:/Users/brian/.heroku/client/lib/heroku/cli.rb:33:in `start'
                 C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'

    Command:     heroku pg:vacuum_stats DATABASE_URL --app <appname>
    Plugins:     heroku-pg-extras
    Version:     heroku/toolbelt/3.11.3 (i386-mingw32) ruby/1.9.3
```

The pg:extras docs show the command "vacuum-stats" and Craig's pages show "vacuum_stats" but both result in the same error.

I'm running:

> heroku --version
> heroku/toolbelt/3.11.3 (i386-mingw32) ruby/1.9.3

**Comment by hheimbuerger** [comment]
Just as an update, this is still the case with Heroku Toolbelt 3.43.3 on Windows 10:

    $> heroku pg:vacuum-stats
    psql: server does not support SSL, but SSL was required
     !    Heroku client internal error.
     !    Search for help at: https://help.heroku.com
     !    Or report a bug at: https://github.com/heroku/heroku/issues/new

        Error:       psql failed. exit status 512, output: "" (RuntimeError)
        Command:     heroku pg:vacuum-stats
        Plugins:     heroku-pg-extras
        Version:     heroku/toolbelt/3.43.3 (i386-mingw32) ruby/1.9.3
        Error ID:    ce99d773abda43b2aca1d9bbfe0250a9


        More information in C:/Users/user/.heroku/error.log

I'm running:

    $> heroku --version
    heroku/toolbelt/3.43.3 (i386-mingw32) ruby/1.9.3
    heroku-cli/5.2.18-f850f09 (windows-386) go1.6.2
    === Installed Plugins
    heroku-pg-extras
