### ISSUE TITLE
Heroku client internal error

### ISSUE THREAD

**Issue by janswist** [heroku/legacy-cli#2054]
Tried to update CLI today. This is what I got:

```
$ heroku update
heroku-cli: Updating plugins... done
heroku-cli: Updating... !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Permission denied @ unlink_internal - C:/Users/Olimpia/AppData/Local/Temp/d20170403-14124-1vwgclr/heroku.zip (Errno::EACCES)
    Command:     heroku update
    Version:     heroku/toolbelt/3.43.16 (i386-mingw32) ruby/2.1.7
    Error ID:    d2390570808840ab890e62e54814339f

    More information in C:/Users/{user}/.heroku/error.log (just below)
```

Error.log:
```
Heroku client internal error.
Permission denied @ unlink_internal - C:/Users/Olimpia/AppData/Local/Temp/d20170403-8952-jq7gmk/heroku.zip
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1460:in `unlink'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1460:in `block in remove_file'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1468:in `platform_support'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1459:in `remove_file'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1448:in `remove'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:776:in `block in remove_entry'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1498:in `block (2 levels) in postorder_traverse'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1502:in `postorder_traverse'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1497:in `block in postorder_traverse'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1496:in `each'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1496:in `postorder_traverse'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:774:in `remove_entry'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:94:in `ensure in mktmpdir'
C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:94:in `mktmpdir'
C:/Users/Olimpia/.heroku/client/lib/heroku/updater.rb:125:in `block in update'
C:/Users/Olimpia/.heroku/client/lib/heroku/updater.rb:92:in `wait_for_lock'
C:/Users/Olimpia/.heroku/client/lib/heroku/updater.rb:121:in `update'
C:/Users/Olimpia/.heroku/client/lib/heroku/command/update.rb:40:in `update_from_url'
C:/Users/Olimpia/.heroku/client/lib/heroku/command/update.rb:21:in `index'
C:/Users/Olimpia/.heroku/client/lib/heroku/command.rb:213:in `run'
C:/Users/Olimpia/.heroku/client/lib/heroku/cli.rb:35:in `start'
C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
```

**Comment by ransombriggs** [comment]
@janswist sorry for the late response.  If you are not using any custom ruby plugins (paste `heroku plugins` if you are uncertain and I can tell you if you are) I would suggest installing from https://cli.heroku.com again, as that removes the ruby code that may be causing this issue.

**Comment by DouglasCAyers** [comment]
I was getting same error as @janswist on Windows 10 64-bit.

Uninstalling `Heroku CLI` and `Heroku Toolbelt` and `Ruby` then [re-installing Heroku CLI](https://devcenter.heroku.com/articles/heroku-cli#download-and-install), as suggested by @ransombriggs, resolved my issue.
