### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by joniba** [heroku/legacy-cli#2056]
heroku-cli: Installing CLI... 18.45MB/18.45MB !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Permission denied @ rb_sysopen - C:\Users\jbena\AppData\Local/heroku/cli/lib/node.exe (Errno::EACCES)
    Command:     heroku logs --tail -a tabit-api-hub
    Version:     heroku/toolbelt/3.43.16 (i386-mingw32) ruby/2.1.7
    Error ID:    1cf1fcb91bf04887b8c9e801794b8140

    More information in C:/Users/jbena/.heroku/error.log

Error log:

> Heroku client internal error.
> Permission denied @ unlink_internal - C:/Users/jbena/AppData/Local/Temp/d20170515-7704-1ore2zi/heroku.zip
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1460:in `unlink'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1460:in `block in remove_file'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1468:in `platform_support'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1459:in `remove_file'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1448:in `remove'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:776:in `block in remove_entry'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1498:in `block (2 levels) in postorder_traverse'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1502:in `postorder_traverse'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1497:in `block in postorder_traverse'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1496:in `each'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:1496:in `postorder_traverse'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/fileutils.rb:774:in `remove_entry'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:94:in `ensure in mktmpdir'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:94:in `mktmpdir'
> C:/Users/jbena/.heroku/client/lib/heroku/updater.rb:125:in `block in update'
> C:/Users/jbena/.heroku/client/lib/heroku/updater.rb:92:in `wait_for_lock'
> C:/Users/jbena/.heroku/client/lib/heroku/updater.rb:121:in `update'
> C:/Users/jbena/.heroku/client/lib/heroku/updater.rb:109:in `rescue in autoupdate'
> C:/Users/jbena/.heroku/client/lib/heroku/updater.rb:105:in `autoupdate'
> C:/Users/jbena/.heroku/client/lib/heroku/cli.rb:36:in `start'
> C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
> Heroku client internal error.
> Permission denied @ rb_sysopen - C:\Users\jbena\AppData\Local/heroku/cli/lib/node.exe
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `initialize'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `open'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `block (4 levels) in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:64:in `each'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:179:in `block (3 levels) in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:28:in `new'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:177:in `block (2 levels) in setup'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:176:in `open'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:176:in `block in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:144:in `setup'
> C:/Users/jbena/.heroku/client/lib/heroku/cli.rb:28:in `start'
> C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
> Heroku client internal error.
> Permission denied @ rb_sysopen - C:\Users\jbena\AppData\Local/heroku/cli/lib/node.exe
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `initialize'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `open'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:188:in `block (4 levels) in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:64:in `each'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:179:in `block (3 levels) in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/rubygems/package/tar_reader.rb:28:in `new'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:177:in `block (2 levels) in setup'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:176:in `open'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:176:in `block in setup'
> C:/Program Files (x86)/Heroku/ruby-2.1.7/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
> C:/Users/jbena/.heroku/client/lib/heroku/jsplugin.rb:144:in `setup'
> C:/Users/jbena/.heroku/client/lib/heroku/cli.rb:28:in `start'
> C:/Program Files (x86)/Heroku/bin/heroku:29:in `<main>'
>

**Comment by dickeyxxx** [comment]
please reinstall, you're using the old CLI
