### ISSUE TITLE
Heroku client internal error

### ISSUE THREAD

**Issue by shoaib-iqbal** [heroku/legacy-cli#2060]
I have installed new heroku cli wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
on Ubuntu 14.04, I am gettig this error when checking heroku --version. 
` !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `length' for nil:NilClass (NoMethodError)
    Command:     heroku login
    Version:     heroku-gem/3.99.1 (x86_64-linux) ruby/2.3.0
    Error ID:    c5991ea9aaaa4c548af66c1befce36bf
`
More error details
`Heroku client internal error.
undefined method `length' for nil:NilClass
/home/irfan/.rvm/gems/ruby-2.3.0/gems/heroku-3.99.1/lib/heroku/auth.rb:188:in `read_credentials'
/home/irfan/.rvm/gems/ruby-2.3.0/gems/heroku-3.99.1/lib/heroku/analytics.rb:53:in `user'
/home/irfan/.rvm/gems/ruby-2.3.0/gems/heroku-3.99.1/lib/heroku/analytics.rb:33:in `skip_analytics'
/home/irfan/.rvm/gems/ruby-2.3.0/gems/heroku-3.99.1/lib/heroku/cli.rb:27:in `start'
/home/irfan/.rvm/gems/ruby-2.3.0/gems/heroku-3.99.1/bin/heroku:26:in `<top (required)>'
/home/irfan/.rvm/gems/ruby-2.3.0/bin/heroku:22:in `load'
/home/irfan/.rvm/gems/ruby-2.3.0/bin/heroku:22:in `<main>'
/home/irfan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/home/irfan/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
`

**Comment by dickeyxxx** [comment]
The CLI is installed as the old legacy gem and is crashing. You need to uninstall the gem or change your path to include the CLI
