### ISSUE TITLE
Heroku Logs Failing in 2.21.1

### ISSUE THREAD

**Issue by jamesward** [heroku/legacy-cli#245]
```
jamesw@T420s:~/projects/shareheroku-java$ heroku logs
/usr/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
from /usr/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
from /usr/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
from /usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
from /usr/lib/ruby/1.9.1/net/http.rb:799:in `connect'
from /usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
from /usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
from /usr/local/heroku/lib/heroku/client.rb:409:in `read_logs'
from /usr/local/heroku/lib/heroku/command/logs.rb:31:in `index'
from /usr/local/heroku/lib/heroku/command.rb:135:in `run'
from /usr/local/heroku/lib/heroku/cli.rb:9:in `start'
from /usr/bin/heroku:30:in `<main>'
```

**Comment by Enelar** [comment]
Still have this issue. How i could develop app without logs?

**Comment by dickeyxxx** [comment]
What version are you on?

**Comment by Enelar** [comment]
dickeyxxx, i am so sorry. it was my fault, later after couple hours of digging google i found post where guy say 'do not use heroku from rubygems on fedora'. So i downloaded original binary from site. (I do not like binary without repotracking)
Current version supplied with official fedora repository
```
Name        : rubygem-heroku
Arch        : noarch
Epoch       : 0
Version     : 3.8.2
Release     : 1.fc21 (<---- !!!! )
Size        : 74 k
Repo        : fedora
Summary     : Client library and CLI to deploy Rails apps on Heroku
URL         : http://heroku.com/
License     : MIT
Description : Client library and command-line tool to manage and deploy Rails apps on
            : Heroku.
```

But
```
[kberezin@kberezin ~]$ uname -r
4.0.5-300.fc22.x86_64
```

Currently i use heroku-toolbelt/3.39.1 (x86_64-linux) ruby/2.2.2 and there no problems.
