### ISSUE TITLE
Encoding error during login

### ISSUE THREAD

**Issue by ddollar** [heroku/legacy-cli#302]
(from the heroku google group)

```
Hi,

I have download and installed Heroku toolbelt and tried to login but I
got the following error once I entered my password. For your
information I already had Git (1.7.10.msysgit.1) and Play framework
(1.2.4) already installed on my PC.

See 'git help <command>' for more information on a specific command.

C:\Users\a*******\workspace_java\StudentApp>heroku login
Enter your Heroku credentials.
Email: *******@******
Password (typing will be hidden):
C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:216:in `glob': code
converter not found (UTF-16LE to IBM737) (Encoding::ConverterNotFoundError)
from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:216:in `associate_or_generate_ssh_key'
from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:212:in `check_for_associated_ssh_key'
from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:206:in `ask_for_and_save_credentials'
from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:59:in `get_credentials'
from C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:22:in `login'
from C:/Program Files (x86)/Heroku/lib/heroku/command/auth.rb:12:in `login'
from C:/Program Files (x86)/Heroku/lib/heroku/command.rb:148:in `run'
from C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:9:in `start'
from C:/Program Files (x86)/Heroku/bin/heroku:28:in `<main>'
```

**Comment by potasmic** [comment]
This problem still persists. 
```
c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tmpdir.rb:15:in `systmpd
ir': code converter not found (UTF-16LE to Windows-1258) (Encoding::ConverterNot
FoundError)
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tmpdir.rb:1
5:in `<class:Dir>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tmpdir.rb:1
3:in `<top (required)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/1.9.1/tempfile.rb
:8:in `<top (required)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.6.7/lib/res
tclient/request.rb:1:in `<top (required)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.6.7/lib/res
tclient.rb:13:in `<top (required)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/vendor/gems/rest-client-1.6.7/lib/res
t_client.rb:2:in `<top (required)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/lib/heroku/client.rb:9:in `<top (requ
ired)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/lib/heroku.rb:1:in `<top (required)>'

        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/lib/heroku/cli.rb:11:in `<top (requir
ed)>'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/site_ruby/1.9.1/r
ubygems/custom_require.rb:36:in `require'
        from c:/Program Files (x86)/Heroku/bin/heroku:27:in `<main>'
```
I'm using Windows 7 Home Premium. I've tried `chcp` and changing my laptop's default locale but none of it works.

**Comment by potasmic** [comment]
Nevermind. It's resolved. I've changed my locale to English (UK) instead of (US)
