### ISSUE TITLE
Heroku client internal error.

### ISSUE THREAD

**Issue by ClaudioFloreani** [heroku/legacy-cli#468]
$ date
Mer 18 Lug 2012 12:06:13 CEST

$ heroku run console --app crevel
Running `console` attached to terminal... up, run.1
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:     Operation timed out - connect(2) (Errno::ETIMEDOUT)
Backtrace: /usr/local/heroku/lib/heroku/client/rendezvous.rb:33:in `initialize'
           /usr/local/heroku/lib/heroku/client/rendezvous.rb:33:in `open'
           /usr/local/heroku/lib/heroku/client/rendezvous.rb:33:in `start'
           /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:67:in `timeout'
           /usr/local/heroku/lib/heroku/client/rendezvous.rb:27:in `start'
           /usr/local/heroku/lib/heroku/command/run.rb:118:in `rendezvous_session'
           /usr/local/heroku/lib/heroku/command/run.rb:104:in `run_attached'
           /usr/local/heroku/lib/heroku/command/run.rb:21:in `index'
           /usr/local/heroku/lib/heroku/command.rb:176:in `send'
           /usr/local/heroku/lib/heroku/command.rb:176:in `run'
           /usr/local/heroku/lib/heroku/cli.rb:13:in `start'
           /usr/bin/heroku:23

Command:   heroku run console --app crevel
Version:   heroku-gem/2.27.3 (universal-darwin11.0) ruby/1.8.7
```

**Comment by jodosha** [comment]
@ddollar Same problem here. `run:detached` trick can work for commands like migrations, but if you need an interactive console, the issue can't be circumvented. Thank you.

**Comment by dickeyxxx** [comment]
there are no plans to change this port

**Comment by jodosha** [comment]
@dickeyxxx Thank you for your answer. I solved the problem using a VPN.
