### ISSUE TITLE
Error:  Proxy is invalid (Excon::Errors::ProxyParseError)

### ISSUE THREAD

**Issue by theskumar** [heroku/legacy-cli#510]
```
Error:       Proxy is invalid (Excon::Errors::ProxyParseError)
Backtrace:   /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:357:in `setup_proxy'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:34:in `initialize'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon.rb:89:in `new'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon.rb:89:in `new'
             /usr/local/heroku/vendor/gems/heroku-api-0.3.2/lib/heroku/api.rb:55:in `initialize'
             /usr/local/heroku/lib/heroku/auth.rb:75:in `new'
             /usr/local/heroku/lib/heroku/auth.rb:75:in `api_key'
             /usr/local/heroku/lib/heroku/auth.rb:185:in `ask_for_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:217:in `ask_for_and_save_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:80:in `get_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:41:in `login'
             /usr/local/heroku/lib/heroku/command/auth.rb:22:in `login'
             /usr/local/heroku/lib/heroku/command.rb:179:in `send'
             /usr/local/heroku/lib/heroku/command.rb:179:in `run'
             /usr/local/heroku/lib/heroku/cli.rb:25:in `start'
             /usr/bin/heroku:25

Command:     heroku login
HTTP Proxy:  
HTTPS Proxy: 
Version:     heroku-toolbelt/2.30.2 (universal-darwin12.0) ruby/1.8.7
```

**Comment by Meshiest** [comment]
omg thank you!

had to remove the exports from my .bashrc as well as the `no_proxy` variable!

**Comment by gangap2014** [comment]
If i want to login into heroku from my linux box that is behind proxy server, how shld i be doing this. 
I have already set http_proxy and https_proxy env var, but still getting this error message.

Thanks..

**Comment by indieNik** [comment]
Hello,

I was trying to run the command behind a corporate firewall. Thanks to this thread I got to know what to set. Solved my problem by setting both HTTP_PROXY and HTTPS_PROXY to **http://proxy.company.com:8080**

Cheers!
