### ISSUE TITLE
Error when backing up using pgbackups

### ISSUE THREAD

**Issue by runlevel5** [heroku/legacy-cli#582]
```
$ heroku pgbackups:capture --expire -a testing-app-123456
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `display_name' for nil:NilClass (NoMethodError)
    Backtrace:   /Users/trungle/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.5/lib/heroku/command/pgbackups.rb:76:in `capture'
                 /Users/trungle/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.5/lib/heroku/command.rb:206:in `run'
                 /Users/trungle/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.5/lib/heroku/cli.rb:28:in `start'
                 /Users/trungle/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.5/bin/heroku:16:in `<top (required)>'
                 /Users/trungle/.rvm/gems/ruby-1.9.3-p194/bin/heroku:23:in `load'
                 /Users/trungle/.rvm/gems/ruby-1.9.3-p194/bin/heroku:23:in `<main>'

    Command:     heroku pgbackups:capture --expire -a testing-app-123456
    Version:     heroku-gem/2.31.5 (x86_64-darwin12.0.0) ruby/1.9.3
```

**Comment by noviceprogram** [comment]
I have the newest version of everything and I still can't upload my database. 
heroku pg:backups restore "URL" DATABASE -a myapp 
Error says "did not find magic strings in the file header"
