### ISSUE TITLE
Getting error while login 

### ISSUE THREAD

**Issue by motyar** [heroku/legacy-cli#671]
Hi Support
I am getting this error while login
Googled it but nothing found that can solve issue. 
Please help me.

C:\Users\dharmmotyar>heroku login
Enter your Heroku credentials.
Email: dharmmotyar@gmail.com
Password (typing will be hidden):
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       Permission denied - connect(2) (Errno::EACCES) (Excon::Errors::SocketError)
Backtrace:   C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:41:in `connect'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:41:in `block (2 levels) in connect'
             C:/Program Files (x86)/ruby-1.9.2/lib/ruby/1.9.1/timeout.rb:58:in `timeout'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:40:in `block in connect'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:29:in `each'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:29:in `connect'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/ssl_socket.rb:74:in `connect'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/socket.rb:16:in `initialize'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/ssl_socket.rb:8:in `initialize'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/connection.rb:364:in `new'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/connection.rb:364:in `socket'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/connection.rb:192:in `request_kernel'
             C:/Program Files (x86)/Heroku/vendor/gems/excon-0.16.8/lib/excon/connection.rb:103:in `request'
             C:/Program Files (x86)/Heroku/vendor/gems/heroku-api-0.3.6/lib/heroku/api.rb:74:in `request'
             C:/Program Files (x86)/Heroku/vendor/gems/heroku-api-0.3.6/lib/heroku/api/login.rb:9:in `post_login'
             C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:80:in `api_key'
             C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:189:in `ask_for_credentials'
             C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:221:in `ask_for_and_save_credentials'
             C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:84:in `get_credentials'
             C:/Program Files (x86)/Heroku/lib/heroku/auth.rb:41:in `login'
             C:/Program Files (x86)/Heroku/lib/heroku/command/auth.rb:31:in `login'
             C:/Program Files (x86)/Heroku/lib/heroku/command.rb:206:in `run'
             C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:28:in `start'
             C:/Program Files (x86)/Heroku/bin/heroku:24:in `<main>'

Command:     heroku login
Version:     heroku/toolbelt/2.33.1 (i386-mingw32) ruby/1.9.2
```

P.S. - I am on windows7 and facing this problem only while working on a dial-up connection, Everything working fine with the broadband.
and
I am able to login in Heroku using Ubuntu on same system with same dial-up connection.

Please help.

Thanks.
-Motyar

**Comment by rnradon** [comment]
Hi,
I get this error while using any heroku command from my linux terminal.
 

SIGILL: illegal instruction
PC=0x5bbadf m=6

goroutine 18 [running]:
crypto/sha256.block(0xc42008b600, 0xc4201ae1e0, 0x80, 0x96)
	/usr/local/go/src/crypto/sha256/sha256block_amd64.s:733 +0x286f fp=0xc42003fb60 sp=0xc42003f938
crypto/sha256.(*digest).Write(0xc42008b600, 0xc4201ae1e0, 0x96, 0x96, 0x0, 0x0, 0x87e738)
	/usr/local/go/src/crypto/sha256/sha256.go:119 +0x120 fp=0xc42003fba8 sp=0xc42003fb60
crypto/tls.(*finishedHash).Write(0xc42003fe48, 0xc4201ae1e0, 0x96, 0x96, 0x846d20, 0xc42008b680, 0x0)
	/usr/local/go/src/crypto/tls/prf.go:229 +0x58 fp=0xc42003fc10 sp=0xc42003fba8
crypto/tls.(*Conn).clientHandshake(0xc420174a80, 0x72def0, 0xc420174b88)
	/usr/local/go/src/crypto/tls/handshake_client.go:206 +0xcfb fp=0xc42003fee0 sp=0xc42003fc10
crypto/tls.(*Conn).Handshake(0xc420174a80, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1260 +0x1b8 fp=0xc42003ff50 sp=0xc42003fee0
net/http.(*Transport).dialConn.func3(0xc420174a80, 0xc4201a6600, 0xc420191ec0)
	/usr/local/go/src/net/http/transport.go:1033 +0x2f fp=0xc42003ff98 sp=0xc42003ff50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003ffa0 sp=0xc42003ff98
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1038 +0xb4f

goroutine 1 [select]:
net/http.(*Transport).getConn(0xc4200d01e0, 0xc42019bb60, 0x0, 0xc42019bac0, 0x5, 0xc42019bb80, 0x12, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:890 +0x9d2
net/http.(*Transport).RoundTrip(0xc4200d01e0, 0xc4200d10e0, 0xc4200d01e0, 0xecfcf9e49, 0x7f7e19f821a1)
	/usr/local/go/src/net/http/transport.go:367 +0x307
net/http.send(0xc4200d0ff0, 0x8423c0, 0xc4200d01e0, 0xecfcf9e49, 0x19f821a1, 0x861de0, 0x8, 0xc42004fa30, 0xc42002e0f0)
	/usr/local/go/src/net/http/client.go:256 +0x15f
net/http.(*Client).send(0xc420015800, 0xc4200d0ff0, 0xecfcf9e49, 0x19f821a1, 0x861de0, 0xc42002e0f0, 0x0, 0x1)
	/usr/local/go/src/net/http/client.go:146 +0x102
net/http.(*Client).doFollowingRedirects(0xc420015800, 0xc4200d0ff0, 0x72d9a8, 0x4, 0xffffffffffffff01, 0xc42004fc40)
	/usr/local/go/src/net/http/client.go:528 +0x5e5
net/http.(*Client).Do(0xc420015800, 0xc4200d0ff0, 0x0, 0x0, 0xc42008b280)
	/usr/local/go/src/net/http/client.go:187 +0x11d
github.com/heroku/cli/vendor/github.com/dghubble/sling.(*Sling).Do(0xc42008b080, 0xc4200d0ff0, 0x697140, 0xc4201aa240, 0x697180, 0xc4201aa250, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/dghubble/sling/sling.go:355 +0x60
github.com/heroku/cli/vendor/github.com/dghubble/sling.(*Sling).Receive(0xc42008b080, 0x697140, 0xc4201aa240, 0x697180, 0xc4201aa250, 0xc42008b080, 0xc4201aa0b0, 0x5)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/dghubble/sling/sling.go:347 +0x7e
main.v2login(0xc42017dfa8, 0x3, 0xc4201aa0b0, 0x5, 0x0, 0x0, 0xc420012240, 0xc42004fdf0)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/auth.go:325 +0x1c3
main.interactiveLogin()
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/auth.go:261 +0x177
main.login(0xc42019d0a0)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/auth.go:208 +0xc2
main.Start(0xc42000c4c0, 0x2, 0x2)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/start.go:70 +0x25e
main.main()
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/main.go:22 +0x9a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive]:
github.com/heroku/cli/vendor/github.com/stvp/rollbar.init.1.func1()
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/stvp/rollbar/rollbar.go:103 +0x55
created by github.com/heroku/cli/vendor/github.com/stvp/rollbar.init.1
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/stvp/rollbar/rollbar.go:114 +0x9d

goroutine 7 [select, locked to thread]:
runtime.gopark(0x72de38, 0x0, 0x705946, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42002cf30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42002cf30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 8 [chan receive]:
main.handleSignal.func1(0xc4200703c0, 0x72d690)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/io.go:316 +0x40
created by main.handleSignal
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/io.go:318 +0xbb

goroutine 9 [chan receive]:
github.com/heroku/cli/vendor/github.com/dickeyxxx/speakeasy.getPassword.func1(0xc420191440, 0xc42019b500, 0x3, 0x3)
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/dickeyxxx/speakeasy/speakeasy_unix.go:48 +0x40
created by github.com/heroku/cli/vendor/github.com/dickeyxxx/speakeasy.getPassword
	/home/ubuntu/.go_workspace/src/github.com/heroku/cli/vendor/github.com/dickeyxxx/speakeasy/speakeasy_unix.go:51 +0x377

goroutine 11 [select]:
net/http.setRequestCancel.func4(0x0, 0xc4201a86f0, 0xc4201a6100, 0xc420191500)
	/usr/local/go/src/net/http/client.go:329 +0x15a
created by net/http.setRequestCancel
	/usr/local/go/src/net/http/client.go:337 +0x29f

goroutine 12 [chan receive]:
net/http.(*Transport).dialConn(0xc4200d01e0, 0x846340, 0xc420010500, 0x0, 0xc42019bac0, 0x5, 0xc42019bb80, 0x12, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1039 +0xb91
net/http.(*Transport).getConn.func4(0xc4200d01e0, 0x846340, 0xc420010500, 0xc4201a8720, 0xc4201915c0)
	/usr/local/go/src/net/http/transport.go:885 +0x78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:887 +0x398

rax    0x6a09e667
rbx    0xbb67ae85
rcx    0x3c6ef372
rdx    0x510e527f
rdi    0x6a09e667
rsi    0x0
rbp    0x7315e0
rsp    0xc42003f938
r8     0xa54ff53a
r9     0x9b05688c
r10    0x1f83d9ab
r11    0x5be0cd19
r12    0x80
r13    0x1680
r14    0x2e
r15    0x8
rip    0x5bbadf
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

Any help is appreciated.
Thank You

**Comment by ransombriggs** [comment]
@rnradon what version of linux are you running?  Could you paste in the contents of the following commands which should help me try and recreate that error.
```
uname -a
cat /etc/lsb-release 
```

**Comment by rnradon** [comment]
output for uname -a => Linux radon 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
output for cat /etc/lsb-release => DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

**Comment by ransombriggs** [comment]
@rnradon could you try running the command again?  I have some leads and knowing if this is intermittent or always happening will help me track things down better.

**Comment by ransombriggs** [comment]
@rnradon could you also include the output of the following command?  I am trying to figure out if this is an architecture support issue, or if it is a programming bug.
```
cat /proc/cpuinfo
```

**Comment by rnradon** [comment]
uname -a  => Linux radon 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release =>DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"


cat /proc/cpuinfo =>
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
stepping	: 3
microcode	: 0x12
cpu MHz		: 1051.781
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust avx2 smep erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4789.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
stepping	: 3
microcode	: 0x12
cpu MHz		: 928.968
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust avx2 smep erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4789.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
stepping	: 3
microcode	: 0x12
cpu MHz		: 1000.031
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust avx2 smep erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4789.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i3-4000M CPU @ 2.40GHz
stepping	: 3
microcode	: 0x12
cpu MHz		: 898.312
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust avx2 smep erms invpcid xsaveopt dtherm arat pln pts
bugs		:
bogomips	: 4789.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:



this is what i am getting.
