### ISSUE TITLE
"Error R13 (Attach error)" when running "heroku run rake db:migrate"

### ISSUE THREAD

**Issue by mockupgo** [heroku/legacy-cli#746]
Hi,

I am trying to migrate my database on my rails app and it is failing. If I look at the logs, I have this:

```
2013-04-05T08:35:39+00:00 heroku[api]: Starting process with command `bundle exec rake db:migrate` by xxx@dadafish.com
2013-04-05T08:35:50+00:00 heroku[run.6819]: Awaiting client
2013-04-05T08:35:50+00:00 heroku[run.6819]: Starting process with command `bundle exec rake db:migrate`
2013-04-05T08:35:50+00:00 heroku[run.6819]: State changed from starting to up
2013-04-05T08:36:20+00:00 heroku[run.6819]: Error R13 (Attach error) -> Failed to attach to process
2013-04-05T08:36:21+00:00 heroku[run.6819]: Process exited with status 128
2013-04-05T08:36:21+00:00 heroku[run.6819]: State changed from up to complete
```

The instance is "dadafish.herokuapp.com"

I have trying multiple times and it is still not working.

If I try to get the bash, same:

```
MacBook-Air-de-Sebastien-Gignoux:dadafish seb$ heroku run bash --app dadafish
Running `bash` attached to terminal... up, run.6041
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       Operation timed out - connect(2) (Errno::ETIMEDOUT)
    Backtrace:   /Users/seb/.heroku/client/lib/heroku/client/rendezvous.rb:39:in `initialize'
                 /Users/seb/.heroku/client/lib/heroku/client/rendezvous.rb:39:in `open'
                 /Users/seb/.heroku/client/lib/heroku/client/rendezvous.rb:39:in `block in start'
                 /usr/local/heroku/ruby/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
                 /Users/seb/.heroku/client/lib/heroku/client/rendezvous.rb:31:in `start'
                 /Users/seb/.heroku/client/lib/heroku/command/run.rb:132:in `rendezvous_session'
                 /Users/seb/.heroku/client/lib/heroku/command/run.rb:119:in `run_attached'
                 /Users/seb/.heroku/client/lib/heroku/command/run.rb:24:in `index'
                 /Users/seb/.heroku/client/lib/heroku/command.rb:206:in `run'
                 /Users/seb/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/local/heroku/bin/heroku:25:in `<main>'

    Command:     heroku run bash --app dadafish
    Plugins:     heroku-accounts
    Version:     heroku-toolbelt/2.37.2 (x86_64-darwin10.8.0) ruby/1.9.3
```

Any helps welcome. Thanks !

Sébastien

**Comment by dunake** [comment]
this is happening to me when i run heroku run rails console 


2016-08-23T06:50:38.477410+00:00 heroku[run.9380]: Awaiting client
2016-08-23T06:50:38.709432+00:00 heroku[run.9380]: State changed from starting to up
2016-08-23T06:51:08.499871+00:00 heroku[run.9380]: State changed from up to complete
2016-08-23T06:51:08.479433+00:00 heroku[run.9380]: Error R13 (Attach error) -> Failed to attach to process
2016-08-23T06:51:08.483254+00:00 heroku[run.9380]: Process exited with status 128

**Comment by dickeyxxx** [comment]
Your CLI is very out of date
