### ISSUE TITLE
heroku fork to Europe fails on heroku-postgresql:dev

### ISSUE THREAD

**Issue by petrbela** [heroku/legacy-cli#775]
```
Adding heroku-postgresql:dev... skipped (Could not communicate with vendor, please try again later)

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

Error:       undefined method `[]' for nil:NilClass (NoMethodError)
Backtrace:   /Users/petrbela/.heroku/client/lib/heroku/command/fork.rb:57:in `block in index'
                 /Users/petrbela/.heroku/client/lib/heroku/command/fork.rb:45:in `each'
                 /Users/petrbela/.heroku/client/lib/heroku/command/fork.rb:45:in `index'
                 /Users/petrbela/.heroku/client/lib/heroku/command.rb:206:in `run'
                 /Users/petrbela/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/bin/heroku:24:in `<main>'
Command:     heroku fork -a kj125-us kj125 --region eu
Plugins:     heroku-config
             heroku-pg-transfer
             heroku-ssl-doctor

Version:     heroku-toolbelt/2.39.0 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by dmcfly85** [comment]
@czhae thanks. Forked worked great after logging in as the admin account
