### ISSUE TITLE
 code converter not found (UTF-16LE to Windows-1258)

### ISSUE THREAD

**Issue by useranalysis** [heroku/legacy-cli#794]
```
Error:       code converter not found (UTF-16LE to Windows-1258) (Encoding::ConverterNotFoundError)
Backtrace:   c:/Program Files/Heroku/lib/heroku/command.rb:13:in `[]'
             c:/Program Files/Heroku/lib/heroku/command.rb:13:in `load'
             c:/Program Files/Heroku/lib/heroku/cli.rb:27:in `start'
             c:/Program Files/Heroku/bin/heroku:29:in `<main>'

Command:     heroku update
Version:     heroku/toolbelt/2.39.0 (i386-mingw32) ruby/1.9.3
```

**Comment by trimble** [comment]
Is this a duplicate of #731?

(They both seem similar to #302, but the issue creation dates make me think that the resolution to #302 evidently didn't completely resolve #731 and this one.)

//cc @katukun @geemus

**Comment by geemus** [comment]
Hard to say. In my experience it usually stemmed from non utf characters for path or username, so some of the changes in the issues your link to work around this by forcing utf. It was always a set of issues I had trouble reproducing, however, so I'm not certain how "solved" it would be here or not.
