### ISSUE TITLE
\xC4" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by dblock** [heroku/legacy-cli#806]
The text being output on the server is "oğlu", heroku logs raises an exception.

```
09:53:44 12299: !    Heroku client internal error.
09:53:44 12299: !    Search for help at: https://help.heroku.com
09:53:44 12299: !    Or report a bug at: https://github.com/heroku/heroku/issues/new
09:53:44 12299: 
09:53:44 12299: Error:       "\xC4" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
09:53:44 12299: Backtrace:   /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers.rb:22:in `write'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers.rb:22:in `puts'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers.rb:22:in `puts'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers.rb:22:in `display'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers/log_displayer.rb:24:in `block in display_logs'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/client.rb:525:in `block (3 levels) in read_logs'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:395:in `call_block'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:386:in `<<'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/protocol.rb:108:in `read_all'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:2763:in `read_body_0'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:2710:in `read_body'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/client.rb:524:in `block (2 levels) in read_logs'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1322:in `block (2 levels) in transport_request'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:2671:in `reading_body'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1321:in `block in transport_request'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1316:in `transport_request'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1293:in `request'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:1195:in `request_get'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/client.rb:523:in `block in read_logs'
09:53:44 12299: /home/jenkins/.rvm/rubies/ruby-1.9.3-p286/lib/ruby/1.9.1/net/http.rb:745:in `start'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/client.rb:522:in `read_logs'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/helpers/log_displayer.rb:19:in `display_logs'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/command/logs.rb:33:in `index'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/command.rb:206:in `run'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/lib/heroku/cli.rb:28:in `start'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/gems/heroku-2.37.2/bin/heroku:17:in `<top (required)>'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/bin/heroku:23:in `load'
09:53:44 12299: /home/jenkins/.rvm/gems/ruby-1.9.3-p286/bin/heroku:23:in `<main>'
09:53:44 12299: 
09:53:44 12299: Command:     heroku logs -p run.8967 --tail --app gravity-production
09:53:44 12299: Version:     heroku-gem/2.37.2 (x86_64-linux) ruby/1.9.3
```

**Comment by jedrekdomanski** [comment]
Did you manage to resovle this problem?

**Comment by dickeyxxx** [comment]
you should not be receiving this error at all anymore, the CLI isn't even written in ruby. Just reinstall it
