### ISSUE TITLE
getaddrinfo: No such host is known.  (SocketError) (Excon::Erro rs::SocketError)

### ISSUE THREAD

**Issue by preetamdamned** [heroku/legacy-cli#830]
```
Enter your Heroku credentials.
Email: preetam.damned@gmail.com
Password (typing will be hidden):**********
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

Error:   getaddrinfo: No such host is known.  (SocketError) (Excon::Errors::SocketError)
Backtrace:   C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/socket.rb:149:in `getaddrinfo'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/socket.rb:149:in`connect'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/ssl_socket.rb:92:in `connect'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/socket.rb:32:in`initialize'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/ssl_socket.rb:8:in `initialize'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/connection.rb:367:in`new'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/connection.rb:367:in `socket'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/connection.rb:105:in`request_call'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/middlewares/mock.rb:42:in `request_call'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/middlewares/instrumentor.rb:22:in`request_call'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/middlewares/base.rb:15:in `request_call'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/middlewares/base.rb:15:in`request_call'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/excon-0.22.1/
lib/excon/connection.rb:246:in `request'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/heroku-api-0.
3.11/lib/heroku/api.rb:76:in`request'
                 C:/Users/Preetam Kumar/.heroku/client/vendor/gems/heroku-api-0.
3.11/lib/heroku/api/login.rb:9:in `post_login'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/auth.rb:80:in
`api_key'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/auth.rb:189:in
 `ask_for_credentials'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/auth.rb:221:in
`ask_for_and_save_credentials'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/auth.rb:84:in
`get_credentials'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/auth.rb:41:in
`login'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/command/auth.r
b:31:in `login'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/command.rb:206
:in`run'
                 C:/Users/Preetam Kumar/.heroku/client/lib/heroku/cli.rb:28:in `
start'
                 C:/Program Files (x86)/Heroku/bin/heroku:29:in`<main>'
```
```
Command:     heroku login
Version:     heroku/toolbelt/2.39.4 (i386-mingw32) ruby/1.9.3
```

**Comment by Sevcansevcan** [comment]
i have the same issue

**Comment by ransombriggs** [comment]
@Sevcansevcan this is almost always a DNS issue, since this issue appears to be against very old code, would you mind pasting the error you receive currently, as well as the output of `heroku version`?

**Comment by Sevcansevcan** [comment]
Hi,

Yes sure I have attached the error code.
You can read the version and some other details in the picture below.

[cid:image001.jpg@01D255F2.DC15F9C0]
