### ISSUE TITLE
64bit Ruby fails to find crtdll.dll

### ISSUE THREAD

**Issue by poke** [heroku/legacy-cli#834]
Follow-up after #832. On the password prompt during `heroku login` I get the following error:

```
C:/Program Files/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `initialize' : No such file or directory (LoadError)
    from C:/Program Files/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `dlopen'
    from C:/Program Files/Ruby200-x64/lib/ruby/2.0.0/Win32API.rb:14:in `initialize'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:197:in `new'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:197:in `ask_for_password_on_windows'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:187:in `ask_for_credentials'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:221:in `ask_for_and_save_credentials'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:84:in `get_credentials'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/auth.rb:41:in `login'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/command/auth.rb:31:in `login'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/command.rb:209:in `run'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/lib/heroku/cli.rb:28:in `start'
    from C:/Program Files/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-2.39.4/bin/heroku:17:in `<top (required)>'
    from C:/Program Files/Ruby200-x64/bin/heroku:23:in `load'
    from C:/Program Files/Ruby200-x64/bin/heroku:23:in `<main>'
```

This seems to happen because the 64bit Ruby cannot locate `crtdll.dll` which is only present in `C:\Windows\SysWOW64\` (the 32bit folder) on my machine. Short code to produce the error is this:

```
require "Win32API"
Win32API.new("crtdll", "_getch", [ ], "L").Call
```

I went back to 32bit Ruby now where it seems to work. It’s a shame that it does not work for a 64bit one though, but I guess it’s more a core Ruby issue. But you might want to rethink the dependency on a DLL.

**Comment by chidumaga** [comment]
@dickeyxxx @blackblood  I have installed via the toolbelt but am still getting the above error. Mine is a 64bit Win 7 running Ruby version 2.1.5. Heroku toolbelt version 3.40.9. Any ideas?
