### ISSUE TITLE
pg:wait can exhaust the rate limit?

### ISSUE THREAD

**Issue by pedro** [heroku/legacy-cli#877]
Reported via support:

```
─(1:100%(0:00):15:36:%)── heroku pg:wait HEROKU_POSTGRESQL_ROSE_URL --remote production 
! Heroku client internal error. 
! Search for help at: https://help.heroku.com 
! Or report a bug at: https://github.com/heroku/heroku/issues/new

Error: uninitialized constant Heroku::API::Errors::RateLimitExceeded (NameError) 
Backtrace: /Users/john/.heroku/client/vendor/gems/heroku-api-0.3.12/lib/heroku/api.rb:91:in `rescue in request' 
/Users/john/.heroku/client/vendor/gems/heroku-api-0.3.12/lib/heroku/api.rb:75:in `request' 
/Users/john/.heroku/client/lib/heroku/auth.rb:20:in `request' 
/Users/john/.heroku/client/vendor/gems/heroku-api-0.3.12/lib/heroku/api/attachments.rb:9:in `get_attachments' 
```

**Comment by JacobEvelyn** [comment]
I noticed this too, and pestered Heroku into adding the `--wait-interval` flag, which you can use to decrease the frequency of polling (default is one second). It's not a great fix but it works.

**Comment by dickeyxxx** [comment]
the flag is probably the best solution for this, but @pedro do you think we should also increase the default polling interval? It's 1 second right now, maybe 2 would be good?

**Comment by JacobEvelyn** [comment]
It seems like since these are database operations it's unlikely an operation will take only a few seconds and more likely to take at least 30 secs at the minimum (only from my small amount of anecdotal evidence).

Why not increase it to 5 or 10 seconds?

**Comment by dickeyxxx** [comment]
5 seems reasonable to me, any thoughts @pedro? maybe @uhoh-itsmaciek?
