### ISSUE TITLE
Exception raised on "heroku pg:ps" command.

### ISSUE THREAD

**Issue by indyarocks** [heroku/legacy-cli#894]
I have pgql installed on my local machine:
$ which psql
/Applications/Postgres.app/Contents/MacOS/bin/psql

I was trying to run "heroku pg:ps" command from my local, and following exception was raised. 

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       undefined method `[]' for nil:NilClass (NoMethodError)
Backtrace:   /Users/Chandan/.heroku/client/lib/heroku/command/pg.rb:336:in `version'
             /Users/Chandan/.heroku/client/lib/heroku/command/pg.rb:341:in `nine_two?'
             /Users/Chandan/.heroku/client/lib/heroku/command/pg.rb:345:in `pid_column'
             /Users/Chandan/.heroku/client/lib/heroku/command/pg.rb:199:in `ps'
             /Users/Chandan/.heroku/client/lib/heroku/command.rb:213:in `run'
             /Users/Chandan/.heroku/client/lib/heroku/cli.rb:28:in `start'
             /usr/bin/heroku:24:in `<main>'

Command:     heroku pg:ps
Version:     heroku-toolbelt/2.40.1 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by trimble** [comment]
@indyarocks, this looks like an old issue. Can we close it?

I tried to recreate:
```
$ heroku pg:ps
 pid  |        state        |      source       |   running_for   | waiting | query 
------+---------------------+-------------------+-----------------+---------+-------
 5374 | idle in transaction | bin/fetch_data.rb | -00:00:00.00138 | f       | BEGIN
(1 row)
```

My system info:
```
heroku-toolbelt/3.43.14 (x86_64-darwin15) ruby/2.3.0
heroku-cli/5.5.3-787d7db (darwin-amd64) go1.7.3

$ which psql
/usr/local/bin/psql
$ psql --version
psql (PostgreSQL) 9.3.2

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.1 (16B2555)
      Kernel Version: Darwin 16.1.0
```
