### ISSUE TITLE
Password (typing will be hidden):  !    Heroku client internal error.

### ISSUE THREAD

**Issue by wilson12** [heroku/legacy-cli#957]
I installed heroku

Fetching: heroku-3.1.0.gem (100%)
 !    The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt
.
 !    Download and install from: https://toolbelt.heroku.com
 !    For API access, see: https://github.com/heroku/heroku.rb
Successfully installed heroku-3.1.0 

THis was successful

 heroku login
DL is deprecated, please use Fiddle
Enter your Heroku credentials.
Email: test@gmail.com
Password (typing will be hidden):  !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       uninitialized constant Heroku::Command::RestClient (NameError)
Backtrace:   c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-3.1.0/lib/heroku
```

/command.rb:220:in `rescue in run'
                 c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-3.1.0/lib/heroku
/command.rb:266:in`run'
                 c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-3.1.0/lib/heroku
/cli.rb:28:in `start'
                 c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/heroku-3.1.0/bin/heroku
:17:in`<top (required)>'
                 c:/Ruby200-x64/bin/heroku:23:in `load'
                 c:/Ruby200-x64/bin/heroku:23:in`<main>'

```
Command:     heroku login
Version:     heroku-gem/3.1.0 (x64-mingw32) ruby/2.0.0
```

**Comment by rochapablo** [comment]
I'm having quite the same problem.

```
$ heroku login
Enter your Heroku credentials.
Email: my@email.com
Password (typing will be hidden):
 !    Invalid identifier.
```

I don't even have the chance of type my password.

```
$ heroku --version
heroku/toolbelt/3.42.25 (i386-mingw32) ruby/2.1.7
heroku-cli/4.27.9-cce0260 (386-windows) go1.5.2
=== Installed Plugins
heroku-apps@1.0.0
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.4
heroku-local@4.1.5
heroku-run@2.9.2
heroku-status@1.2.4
```

**Comment by ransombriggs** [comment]
@rochapablo Are you using cygwin or git bash or cmd.exe?

**Comment by rochapablo** [comment]
git bash

**Comment by karduk** [comment]
Had the same error with git bash prompt but when i changed to command prompt with ruby on rails i was able to type the password.

**Comment by rochapablo** [comment]
Uhnnn, I'll check that.

Thank you.

**Comment by 1eandro** [comment]
I'm facing the same problem

**Comment by ransombriggs** [comment]
@1eandro Sorry for the late response, but can you paste the output of `heroku version` and the output from `heroku login` (I am assuming you were getting this error when you ran `heroku login`, but if it is from a different command, you can run that instead).

**Comment by 1eandro** [comment]
Hello @ransombriggs, thank you for your response.

Here is the output of 'heroku version':

$ heroku version
heroku/toolbelt/3.42.29 (i386-mingw32) ruby/2.1.7
heroku-cli/4.27.14-a663ce1 (386-windows) go1.5.3
=== Installed Plugins
heroku-apps@1.1.3
heroku-cli-addons@0.1.1
heroku-fork@4.0.0
heroku-git@2.4.4
heroku-local@4.1.5
heroku-run@2.9.2
heroku-spaces@2.0.9
heroku-status@1.2.4

heroku-cli: Updating... done.



And the problem of not being possible to type the password can be seen in this picture http://s10.postimg.org/fkf334ss9/the_error.png

After I type my email I press enter and then (as shown in the picture) I receive an 'Invalid identifier' error.

However, the 'hehoru login' command works fine using windows powershell, or even windows cmd

**Comment by ransombriggs** [comment]
This is a known issue with heroku login and cygwin or git bash heroku/heroku-cli#84 .  I am not sure why you did not receive the more helpful error message `Login is currently incompatible with git bash/Cygwin` but the underlying problem is that we cannot turn off echo easily for the password prompt as stdin is not a tty, but a pipe.

**Comment by matalonga** [comment]
@1eandro @rochapablo  i am having the same problem. How have you solved this problem? How can i change from git bash to git cmd?

Thanks

**Comment by ransombriggs** [comment]
@matalonga The location of the windows cmd depends on your version of Windows, but usually it is under `Start Menu -> All Programs -> Accessories -> Command Prompt`.  If you open that up and run `heroku login` it should succeed as expected.  This will log you in and save your API token to your filesystem, at which point you can switch back to `git bash` if you wish to.

**Comment by rochapablo** [comment]
Unfortunately I'm still logged through the cmd, I'm sure that happened for some mistaken that I did installing and uninstalling the git.

Sorry.
