### ISSUE TITLE
Error installing SSL 

### ISSUE THREAD

**Issue by pfrank8** [heroku/legacy-cli#983]
I tried to install a cert for cc.goodlabs.io (heroku app charity-checkout-prod).  I got an error that I had the wrong domain on the cert (I don't think that's the case), now getting a client error after any commands.  

Peters-MacBook-Pro:cc_shopify peterfranklin$ heroku addons:add ssl:endpoint
Adding ssl:endpoint on charity-checkout-stage... failed
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       hostname does not match the server certificate (OpenSSL::SSL::SSLError)
Backtrace:   /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/ssl-internal.rb:121:in `post_connection_check'
             /usr/local/heroku/ruby/lib/ruby/1.9.1/net/http.rb:801:in `connect'
             /usr/local/heroku/ruby/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
             /usr/local/heroku/ruby/lib/ruby/1.9.1/net/http.rb:744:in `start'
             /Users/peterfranklin/.heroku/client/vendor/gems/rest-client-1.6.7/lib/restclient/request.rb:172:in `transmit'
             /Users/peterfranklin/.heroku/client/vendor/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
             /Users/peterfranklin/.heroku/client/vendor/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
             /Users/peterfranklin/.heroku/client/vendor/gems/rest-client-1.6.7/lib/restclient/resource.rb:67:in `post'
             /Users/peterfranklin/.heroku/client/lib/heroku/client.rb:620:in `process'
             /Users/peterfranklin/.heroku/client/lib/heroku/client.rb:602:in `post'
             /Users/peterfranklin/.heroku/client/lib/heroku/client.rb:691:in `update_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/client.rb:672:in `configure_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/client.rb:561:in `install_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:73:in `block in add'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:289:in `call'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:289:in `block (2 levels) in configure_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:229:in `addon_run'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:289:in `block in configure_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/helpers.rb:237:in `action'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:288:in `configure_addon'
             /Users/peterfranklin/.heroku/client/lib/heroku/command/addons.rb:72:in `add'
             /Users/peterfranklin/.heroku/client/lib/heroku/command.rb:218:in `run'
             /Users/peterfranklin/.heroku/client/lib/heroku/cli.rb:28:in `start'
             /usr/bin/heroku:24:in `<main>'

Command:     heroku addons:add ssl:endpoint
Plugins:     heroku-pipeline
Version:     heroku-toolbelt/3.2.1 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by majianxiong** [comment]
How to solve the
