### ISSUE TITLE
client internal error after successful authentication

### ISSUE THREAD

**Issue by twohey** [heroku/legacy-cli#994]
I'm reporting this as the tool asked. Also, running `heroku apps` again (this would be the second time after a successful authentication) produced no errors.

```
Authentication successful.
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       EOFError (EOFError) (Excon::Errors::SocketError)
    Backtrace:   /usr/local/heroku/ruby/lib/ruby/1.9.1/openssl/buffering.rb:246:in `readline'
                 /Users/twohey/.heroku/client/vendor/gems/excon-0.25.3/lib/excon/response.rb:39:in `parse'
                 /Users/twohey/.heroku/client/vendor/gems/excon-0.25.3/lib/excon/middlewares/response_parser.rb:6:in `response_call'
                 /Users/twohey/.heroku/client/vendor/gems/excon-0.25.3/lib/excon/connection.rb:349:in `response'
                 /Users/twohey/.heroku/client/vendor/gems/excon-0.25.3/lib/excon/connection.rb:247:in `request'
                 /Users/twohey/.heroku/client/lib/heroku/client/organizations.rb:31:in `request'
                 /Users/twohey/.heroku/client/lib/heroku/client/organizations.rb:76:in `get_orgs'
                 /Users/twohey/.heroku/client/lib/heroku/command/base.rb:53:in `org'
                 /Users/twohey/.heroku/client/lib/heroku/command/apps.rb:29:in `index'
                 /Users/twohey/.heroku/client/lib/heroku/command.rb:218:in `run'
                 /Users/twohey/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/local/heroku/bin/heroku:24:in `<main>'

    Command:     heroku apps
    Version:     heroku-toolbelt/3.2.2 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by twohey** [comment]
This is a legacy project and no progress has happened for over 3 years. Closing as it appears the underlying issue will not be fixed and may not exist in the new CLI.
